// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: src/grpc_control/market_observer.proto

package grpc_control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*SourceStatus        `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{0}
}

func (x *ListSourcesResponse) GetSources() []*SourceStatus {
	if x != nil {
		return x.Sources
	}
	return nil
}

type AddSourceRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // e.g., "yahoo"
	Symbols               []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	UpdateIntervalSeconds int32                  `protobuf:"varint,4,opt,name=update_interval_seconds,json=updateIntervalSeconds,proto3" json:"update_interval_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddSourceRequest) Reset() {
	*x = AddSourceRequest{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceRequest) ProtoMessage() {}

func (x *AddSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceRequest.ProtoReflect.Descriptor instead.
func (*AddSourceRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{1}
}

func (x *AddSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSourceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddSourceRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AddSourceRequest) GetUpdateIntervalSeconds() int32 {
	if x != nil {
		return x.UpdateIntervalSeconds
	}
	return 0
}

type RemoveSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSourceRequest) Reset() {
	*x = RemoveSourceRequest{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSourceRequest) ProtoMessage() {}

func (x *RemoveSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSourceRequest.ProtoReflect.Descriptor instead.
func (*RemoveSourceRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"` // e.g., "yahoo"
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`                         // New full list of symbols
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSymbolsRequest) Reset() {
	*x = UpdateSymbolsRequest{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSymbolsRequest) ProtoMessage() {}

func (x *UpdateSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSymbolsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSymbolsRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *UpdateSymbolsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type UpdateSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SymbolCount   int32                  `protobuf:"varint,3,opt,name=symbol_count,json=symbolCount,proto3" json:"symbol_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSymbolsResponse) Reset() {
	*x = UpdateSymbolsResponse{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSymbolsResponse) ProtoMessage() {}

func (x *UpdateSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSymbolsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSymbolsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSymbolsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateSymbolsResponse) GetSymbolCount() int32 {
	if x != nil {
		return x.SymbolCount
	}
	return 0
}

type SourceControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceControlRequest) Reset() {
	*x = SourceControlRequest{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceControlRequest) ProtoMessage() {}

func (x *SourceControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceControlRequest.ProtoReflect.Descriptor instead.
func (*SourceControlRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{5}
}

func (x *SourceControlRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

type SourceControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentState  string                 `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"` // "running", "stopped", "removed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceControlResponse) Reset() {
	*x = SourceControlResponse{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceControlResponse) ProtoMessage() {}

func (x *SourceControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceControlResponse.ProtoReflect.Descriptor instead.
func (*SourceControlResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{6}
}

func (x *SourceControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SourceControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SourceControlResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{7}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*SourceStatus        `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetSources() []*SourceStatus {
	if x != nil {
		return x.Sources
	}
	return nil
}

type SourceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsRunning     bool                   `protobuf:"varint,2,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	SymbolCount   int32                  `protobuf:"varint,3,opt,name=symbol_count,json=symbolCount,proto3" json:"symbol_count,omitempty"`
	IsRealTime    bool                   `protobuf:"varint,4,opt,name=is_real_time,json=isRealTime,proto3" json:"is_real_time,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatus) Reset() {
	*x = SourceStatus{}
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatus) ProtoMessage() {}

func (x *SourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_control_market_observer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatus.ProtoReflect.Descriptor instead.
func (*SourceStatus) Descriptor() ([]byte, []int) {
	return file_src_grpc_control_market_observer_proto_rawDescGZIP(), []int{9}
}

func (x *SourceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceStatus) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *SourceStatus) GetSymbolCount() int32 {
	if x != nil {
		return x.SymbolCount
	}
	return 0
}

func (x *SourceStatus) GetIsRealTime() bool {
	if x != nil {
		return x.IsRealTime
	}
	return false
}

func (x *SourceStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_src_grpc_control_market_observer_proto protoreflect.FileDescriptor

const file_src_grpc_control_market_observer_proto_rawDesc = "" +
	"\n" +
	"&src/grpc_control/market_observer.proto\x12\acontrol\"F\n" +
	"\x13ListSourcesResponse\x12/\n" +
	"\asources\x18\x01 \x03(\v2\x15.control.SourceStatusR\asources\"\x8c\x01\n" +
	"\x10AddSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\asymbols\x18\x03 \x03(\tR\asymbols\x126\n" +
	"\x17update_interval_seconds\x18\x04 \x01(\x05R\x15updateIntervalSeconds\")\n" +
	"\x13RemoveSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Q\n" +
	"\x14UpdateSymbolsRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\"n\n" +
	"\x15UpdateSymbolsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fsymbol_count\x18\x03 \x01(\x05R\vsymbolCount\"7\n" +
	"\x14SourceControlRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\"p\n" +
	"\x15SourceControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\"\a\n" +
	"\x05Empty\"A\n" +
	"\x0eStatusResponse\x12/\n" +
	"\asources\x18\x01 \x03(\v2\x15.control.SourceStatusR\asources\"\x9a\x01\n" +
	"\fSourceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_running\x18\x02 \x01(\bR\tisRunning\x12!\n" +
	"\fsymbol_count\x18\x03 \x01(\x05R\vsymbolCount\x12 \n" +
	"\fis_real_time\x18\x04 \x01(\bR\n" +
	"isRealTime\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type2\xd5\x03\n" +
	"\x15MarketObserverControl\x12N\n" +
	"\rUpdateSymbols\x12\x1d.control.UpdateSymbolsRequest\x1a\x1e.control.UpdateSymbolsResponse\x12L\n" +
	"\vStartSource\x12\x1d.control.SourceControlRequest\x1a\x1e.control.SourceControlResponse\x12K\n" +
	"\n" +
	"StopSource\x12\x1d.control.SourceControlRequest\x1a\x1e.control.SourceControlResponse\x12;\n" +
	"\vListSources\x12\x0e.control.Empty\x1a\x1c.control.ListSourcesResponse\x12F\n" +
	"\tAddSource\x12\x19.control.AddSourceRequest\x1a\x1e.control.SourceControlResponse\x12L\n" +
	"\fRemoveSource\x12\x1c.control.RemoveSourceRequest\x1a\x1e.control.SourceControlResponseB\x14Z\x12./src/grpc_controlb\x06proto3"

var (
	file_src_grpc_control_market_observer_proto_rawDescOnce sync.Once
	file_src_grpc_control_market_observer_proto_rawDescData []byte
)

func file_src_grpc_control_market_observer_proto_rawDescGZIP() []byte {
	file_src_grpc_control_market_observer_proto_rawDescOnce.Do(func() {
		file_src_grpc_control_market_observer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_grpc_control_market_observer_proto_rawDesc), len(file_src_grpc_control_market_observer_proto_rawDesc)))
	})
	return file_src_grpc_control_market_observer_proto_rawDescData
}

var file_src_grpc_control_market_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_src_grpc_control_market_observer_proto_goTypes = []any{
	(*ListSourcesResponse)(nil),   // 0: control.ListSourcesResponse
	(*AddSourceRequest)(nil),      // 1: control.AddSourceRequest
	(*RemoveSourceRequest)(nil),   // 2: control.RemoveSourceRequest
	(*UpdateSymbolsRequest)(nil),  // 3: control.UpdateSymbolsRequest
	(*UpdateSymbolsResponse)(nil), // 4: control.UpdateSymbolsResponse
	(*SourceControlRequest)(nil),  // 5: control.SourceControlRequest
	(*SourceControlResponse)(nil), // 6: control.SourceControlResponse
	(*Empty)(nil),                 // 7: control.Empty
	(*StatusResponse)(nil),        // 8: control.StatusResponse
	(*SourceStatus)(nil),          // 9: control.SourceStatus
}
var file_src_grpc_control_market_observer_proto_depIdxs = []int32{
	9, // 0: control.ListSourcesResponse.sources:type_name -> control.SourceStatus
	9, // 1: control.StatusResponse.sources:type_name -> control.SourceStatus
	3, // 2: control.MarketObserverControl.UpdateSymbols:input_type -> control.UpdateSymbolsRequest
	5, // 3: control.MarketObserverControl.StartSource:input_type -> control.SourceControlRequest
	5, // 4: control.MarketObserverControl.StopSource:input_type -> control.SourceControlRequest
	7, // 5: control.MarketObserverControl.ListSources:input_type -> control.Empty
	1, // 6: control.MarketObserverControl.AddSource:input_type -> control.AddSourceRequest
	2, // 7: control.MarketObserverControl.RemoveSource:input_type -> control.RemoveSourceRequest
	4, // 8: control.MarketObserverControl.UpdateSymbols:output_type -> control.UpdateSymbolsResponse
	6, // 9: control.MarketObserverControl.StartSource:output_type -> control.SourceControlResponse
	6, // 10: control.MarketObserverControl.StopSource:output_type -> control.SourceControlResponse
	0, // 11: control.MarketObserverControl.ListSources:output_type -> control.ListSourcesResponse
	6, // 12: control.MarketObserverControl.AddSource:output_type -> control.SourceControlResponse
	6, // 13: control.MarketObserverControl.RemoveSource:output_type -> control.SourceControlResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_grpc_control_market_observer_proto_init() }
func file_src_grpc_control_market_observer_proto_init() {
	if File_src_grpc_control_market_observer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_grpc_control_market_observer_proto_rawDesc), len(file_src_grpc_control_market_observer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_control_market_observer_proto_goTypes,
		DependencyIndexes: file_src_grpc_control_market_observer_proto_depIdxs,
		MessageInfos:      file_src_grpc_control_market_observer_proto_msgTypes,
	}.Build()
	File_src_grpc_control_market_observer_proto = out.File
	file_src_grpc_control_market_observer_proto_goTypes = nil
	file_src_grpc_control_market_observer_proto_depIdxs = nil
}
