// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: src/grpc_control/market_observer.proto

package grpc_control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketObserverControl_UpdateSymbols_FullMethodName = "/control.MarketObserverControl/UpdateSymbols"
	MarketObserverControl_StartSource_FullMethodName   = "/control.MarketObserverControl/StartSource"
	MarketObserverControl_StopSource_FullMethodName    = "/control.MarketObserverControl/StopSource"
	MarketObserverControl_ListSources_FullMethodName   = "/control.MarketObserverControl/ListSources"
	MarketObserverControl_AddSource_FullMethodName     = "/control.MarketObserverControl/AddSource"
	MarketObserverControl_RemoveSource_FullMethodName  = "/control.MarketObserverControl/RemoveSource"
)

// MarketObserverControlClient is the client API for MarketObserverControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketObserverControlClient interface {
	// Update the list of symbols for a specific data source
	UpdateSymbols(ctx context.Context, in *UpdateSymbolsRequest, opts ...grpc.CallOption) (*UpdateSymbolsResponse, error)
	// Start a specific data source
	StartSource(ctx context.Context, in *SourceControlRequest, opts ...grpc.CallOption) (*SourceControlResponse, error)
	// Stop a specific data source
	StopSource(ctx context.Context, in *SourceControlRequest, opts ...grpc.CallOption) (*SourceControlResponse, error)
	// List all available data sources
	ListSources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	// Dynamically add a new data source
	AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*SourceControlResponse, error)
	// Dynamically remove a data source
	RemoveSource(ctx context.Context, in *RemoveSourceRequest, opts ...grpc.CallOption) (*SourceControlResponse, error)
}

type marketObserverControlClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketObserverControlClient(cc grpc.ClientConnInterface) MarketObserverControlClient {
	return &marketObserverControlClient{cc}
}

func (c *marketObserverControlClient) UpdateSymbols(ctx context.Context, in *UpdateSymbolsRequest, opts ...grpc.CallOption) (*UpdateSymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSymbolsResponse)
	err := c.cc.Invoke(ctx, MarketObserverControl_UpdateSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketObserverControlClient) StartSource(ctx context.Context, in *SourceControlRequest, opts ...grpc.CallOption) (*SourceControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlResponse)
	err := c.cc.Invoke(ctx, MarketObserverControl_StartSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketObserverControlClient) StopSource(ctx context.Context, in *SourceControlRequest, opts ...grpc.CallOption) (*SourceControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlResponse)
	err := c.cc.Invoke(ctx, MarketObserverControl_StopSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketObserverControlClient) ListSources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, MarketObserverControl_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketObserverControlClient) AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*SourceControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlResponse)
	err := c.cc.Invoke(ctx, MarketObserverControl_AddSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketObserverControlClient) RemoveSource(ctx context.Context, in *RemoveSourceRequest, opts ...grpc.CallOption) (*SourceControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlResponse)
	err := c.cc.Invoke(ctx, MarketObserverControl_RemoveSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketObserverControlServer is the server API for MarketObserverControl service.
// All implementations must embed UnimplementedMarketObserverControlServer
// for forward compatibility.
type MarketObserverControlServer interface {
	// Update the list of symbols for a specific data source
	UpdateSymbols(context.Context, *UpdateSymbolsRequest) (*UpdateSymbolsResponse, error)
	// Start a specific data source
	StartSource(context.Context, *SourceControlRequest) (*SourceControlResponse, error)
	// Stop a specific data source
	StopSource(context.Context, *SourceControlRequest) (*SourceControlResponse, error)
	// List all available data sources
	ListSources(context.Context, *Empty) (*ListSourcesResponse, error)
	// Dynamically add a new data source
	AddSource(context.Context, *AddSourceRequest) (*SourceControlResponse, error)
	// Dynamically remove a data source
	RemoveSource(context.Context, *RemoveSourceRequest) (*SourceControlResponse, error)
	mustEmbedUnimplementedMarketObserverControlServer()
}

// UnimplementedMarketObserverControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketObserverControlServer struct{}

func (UnimplementedMarketObserverControlServer) UpdateSymbols(context.Context, *UpdateSymbolsRequest) (*UpdateSymbolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSymbols not implemented")
}
func (UnimplementedMarketObserverControlServer) StartSource(context.Context, *SourceControlRequest) (*SourceControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSource not implemented")
}
func (UnimplementedMarketObserverControlServer) StopSource(context.Context, *SourceControlRequest) (*SourceControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSource not implemented")
}
func (UnimplementedMarketObserverControlServer) ListSources(context.Context, *Empty) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedMarketObserverControlServer) AddSource(context.Context, *AddSourceRequest) (*SourceControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSource not implemented")
}
func (UnimplementedMarketObserverControlServer) RemoveSource(context.Context, *RemoveSourceRequest) (*SourceControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSource not implemented")
}
func (UnimplementedMarketObserverControlServer) mustEmbedUnimplementedMarketObserverControlServer() {}
func (UnimplementedMarketObserverControlServer) testEmbeddedByValue()                               {}

// UnsafeMarketObserverControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketObserverControlServer will
// result in compilation errors.
type UnsafeMarketObserverControlServer interface {
	mustEmbedUnimplementedMarketObserverControlServer()
}

func RegisterMarketObserverControlServer(s grpc.ServiceRegistrar, srv MarketObserverControlServer) {
	// If the following call pancis, it indicates UnimplementedMarketObserverControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketObserverControl_ServiceDesc, srv)
}

func _MarketObserverControl_UpdateSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketObserverControlServer).UpdateSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketObserverControl_UpdateSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketObserverControlServer).UpdateSymbols(ctx, req.(*UpdateSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketObserverControl_StartSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketObserverControlServer).StartSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketObserverControl_StartSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketObserverControlServer).StartSource(ctx, req.(*SourceControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketObserverControl_StopSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketObserverControlServer).StopSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketObserverControl_StopSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketObserverControlServer).StopSource(ctx, req.(*SourceControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketObserverControl_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketObserverControlServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketObserverControl_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketObserverControlServer).ListSources(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketObserverControl_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketObserverControlServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketObserverControl_AddSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketObserverControlServer).AddSource(ctx, req.(*AddSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketObserverControl_RemoveSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketObserverControlServer).RemoveSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketObserverControl_RemoveSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketObserverControlServer).RemoveSource(ctx, req.(*RemoveSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketObserverControl_ServiceDesc is the grpc.ServiceDesc for MarketObserverControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketObserverControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.MarketObserverControl",
	HandlerType: (*MarketObserverControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSymbols",
			Handler:    _MarketObserverControl_UpdateSymbols_Handler,
		},
		{
			MethodName: "StartSource",
			Handler:    _MarketObserverControl_StartSource_Handler,
		},
		{
			MethodName: "StopSource",
			Handler:    _MarketObserverControl_StopSource_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _MarketObserverControl_ListSources_Handler,
		},
		{
			MethodName: "AddSource",
			Handler:    _MarketObserverControl_AddSource_Handler,
		},
		{
			MethodName: "RemoveSource",
			Handler:    _MarketObserverControl_RemoveSource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/grpc_control/market_observer.proto",
}
